---
# This Playbook deploys Authentication/Authorization client

- hosts: auth-client
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles: 
    - {role: sssd, when: auth_client_include_sssd}
  tasks:
    - include: tasks/main.yml
  handlers:
   - include: handlers/main.yml
